version: "3.8"
services:

    # PHP Service
    php:
      image: laravel-app
      build:
        context: ./laravel-app
      env_file: "laravel-app/.env"
      depends_on:
        mysql:
          condition: service_healthy
      ports:
          - 8001:8000
    mysql:
      image: mysql:latest
      restart: always
      container_name: mysql
      environment:
        MYSQL_DATABASE: 'laravel'
        MYSQL_ROOT_PASSWORD: '123'
      healthcheck:
        test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
        interval: 10s
        timeout: 5s
        retries: 3
      ports:
        - "3306:3306"
    redis:
      image: redis:latest
      container_name: redis
      environment:
        # ALLOW_EMPTY_PASSWORD is recommended only for development.
        - ALLOW_EMPTY_PASSWORD=yes
          #- REDIS_DISABLE_COMMANDS=FLUSHDB,FLUSHALL
      ports:
        - '6379:6379'